import { NeighborhoodDto } from "src/app/autogenerated/clients";

export class Neighborhood {
  id?: number;
  name?: string;

  constructor(dto? : NeighborhoodDto) {
    if (dto) {
      this.id = dto.id;
      this.name = dto.name;
    }
  }

}
