import { Injectable } from '@angular/core';
import { Resolve } from '@angular/router';

import { map, Observable} from 'rxjs';
import { NeighborhoodsClient } from '../autogenerated/clients';
import { Neighborhood } from './models/neighborhood';

@Injectable({
  providedIn: 'root'
})
export class NeighborhoodsResolver implements Resolve<Observable<Neighborhood[]>> {

  constructor(private service: NeighborhoodsClient) {

  }

  resolve(): Observable<Neighborhood[]> {
    return this.service.getNeighborhoods().pipe(map((dto) => dto.map((n) => new Neighborhood(n))));
  }
}
